### ISSUE TITLE
Story: Basic Results Page 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/sitewide-search-app#1]
## As a user, I want to be able to see my search results, navigate to the results items and know if an item is an infographic or video page so that I may easily find the content I am searching for.

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: English Results Page
  Given user navigates to "/?swKeyword=breast cancer"
  Then the system returns the results page for breast cancer
    Then the system returns the results page
      And the H1 on the results page is “<H1 for results page>”
      And the system displays “Results for: breast cancer” as an H3
      And the system displays the first page of results with “Results 1–20 of [total results returned] for: breast cancer” as an H4
        Where total results returned is the total number of results returned from the API
      And the system defaults to display 20 results per page
      And each result item displays the browser title of the content item as a clickable link to the item
      And each result item does not display "- National Cancer Institute" after the title
      And each result item displays the meta-description below the clickable link
      And each result item displays the full URL below the meta-description
Examples:
|url| |H1 for results page|
|cancer.gov| |NCI Search Results|
|dceg.cancer.gov| |DCEG Search Results|
|cancer.gov/nano| |NSDB Search Results|
|cancer.gov/pediatric-adult-rare-tumor| |MyPART Search Results|
|cancer.gov/rare-brain-spine-tumor/| |Rare Brain and Spine Tumor Search Results|
```

```gherkin
Scenario: Spanish Results Page 
  Given language is set to “es”
  Given user navigates to "/?swKeyword=cáncer de células"
  Then the system returns the results page for cáncer de células
       And the H1 on the results page is “<H1 on results page>”
       And the system displays “Resultados para: cáncer de células” as an H3
       And the system displays the first page of results with “Resultados 1–20 de [total results returned] para: cáncer de células” as an H4
         Where total results returned is the total number of results returned from the API
       And the system defaults to display 20 results per page
       And each result item displays the browser title of the content item as a clickable link to the item
       And each result item does not display "- Instituto Nacional del Cáncer" after the title
       And each result item displays the meta-description below the clickable link
       And each result item displays the full URL below the meta-description
Examples
|url| |H1 on results page|
|cancer.gov/espanol| |Resultados|
| cancer.gov/rare-brain-spine-tumor/espanol || Tumores infrecuentes de cerebro y médula espinal resultados|
```
```gherkin
Scenario: Infographic English Search 
  Given user navigates to "/?swKeyword=infographic"
  Then the system returns the results page for infographic
     And the H1 on the results page is “<H1 for results page>”
     And the system displays “Results for: infographic”
     And the system displays the first page of results with the label “Results 1–20 of [total results returned] for: infographic”
       Where total results returned is the total number of results returned from the API
     And the system displays 20 results per page
     And if the result is an infographic content type
       Then the result item displays the browser title of the content item as a clickable link to the item
       And each result item does not display "- National Cancer Institute" after the title
       And the result item displays an “(Infographic)” label beside the clickable link
       And the result item displays the meta-description below the clickable link
       And the result item displays the full URL below the meta-description
Examples:
|url| |H1 for results page|
|cancer.gov| |NCI Search Results|
|dceg.cancer.gov| |DCEG Search Results|
|cancer.gov/nano| |NSDB Search Results|
|cancer.gov/pediatric-adult-rare-tumor| |MyPART Search Results|
|cancer.gov/rare-brain-spine-tumor/| | Rare Brain and Spine Tumor Search Results|
```

```gherkin
Scenario: Infographic Spanish Search 
  Given language is set to “es”
  Given user navigates to "/?swKeyword=infografía"
  Then the system returns the results page for infografía
      And the H1 on the results page is “Resultados”
       And the system displays “Resultados para: infografía”
       And the system displays the first page of results with the label “Resultados 1–20 de [total results returned] para: infografía”
         Where total results returned is the total number of results returned from the API
       And the system displays 20 results per page
       And if the result is an infographic content type
         Then the result item displays the browser title of the content item as a clickable link to the item
         And each result item does not display "- Instituto Nacional del Cáncer" after the title
         And the result item displays an “(Infografía)” label beside the clickable link
         And the result item displays the meta-description below the clickable link
         And the result item displays the full URL below the meta-description
Examples
|url| |H1 on results page|
|cancer.gov/espanol| |Resultados|
| cancer.gov/rare-brain-spine-tumor/espanol || Tumores infrecuentes de cerebro y médula espinal resultados|
```
```gherkin
Scenario: Video English Search 
  Given user navigates to "/?swKeyword=understanding your cancer prognosis"
  Then the system returns the results page for understanding your cancer prognosis
    Then the system returns the results page
       And the H1 on the results page is “NCI Search Results”
       And the system displays “Results for: <”search term example”>”
       And the system displays the first page of results with the label “Results 1–20 of [total results returned] for: <”search term example”>”
         Where total results returned is the total number of results returned from the API
       And the system displays 20 results per page
       And if the result is a video content type
         Then the result item displays the browser title of the content item as a clickable link to the item
         And each result item does not display "- National Cancer Institute" after the title
         And the result item displays an “(Video)” label beside the clickable link
         And the result item displays the meta-description below the clickable link
         And the result item displays the full URL below the meta-description
Examples
|url| |search term example| |H1 for results page|
|cancer.gov| |understanding your cancer prognosis| |NCI Search Results|
|dceg.cancer.gov| | dceg fellowship program| |DCEG Search Results|
| cancer.gov/nano| |video journey| |NSDB Search Results|
| cancer.gov/pediatric-adult-rare-tumor|| Selumetinib shrinks pediatric tumors| |MyPART Search Results|
| cancer.gov/rare-brain-spine-tumor/| |overview| | Rare Brain and Spine Tumor Search Results|
```

```gherkin
Scenario: Spanish Video Search
  Given language is set to “es”
  Given user navigates to "/?swKeyword=video"
  Then the system returns the results page for video
       And the H1 on the results page is “<H1 on results page>”
       And the system displays “Resultados para: <search term>”
       And the system displays the first page of results with the label “Resultados 1–20 de [total results returned] para: <search term>”
         Where total results returned is the total number of results returned from the API
       And the system displays 20 results per page
       And if the result is a video content type
         Then the result item displays the browser title of the content item as a clickable link to the item
         And each result item does not display "- Instituto Nacional del Cáncer" after the title
         And the result item displays an “(Video)” label beside the clickable link
         And the result item displays the meta-description below the clickable link
         And the result item displays the full URL below the meta-description
Examples
|url| |search term| |H1 on results page|
|cancer.gov/espanol| |video| |Resultados|
| cancer.gov/rare-brain-spine-tumor/espanol| |no examples exist on prod|| Tumores infrecuentes de cerebro y médula espinal resultados|

```

```gherkin
Scenario: Results page metadata
  Given user is viewing the results page on any site
    Then <meta name="robots" content="noindex" /> exists in the data for the page 
```

```gherkin
Scenario: Page Load Analytics fires when a user views a "starts with" search result page
  Given "resultsPageTitle" is set to "NCI Search Results"
    And "searchCollection" is set to "cgov"
    And "language" is set to "en"
    And "baseHost" is set to "http://localhost:3000"
    And "canonicalHost" is set to "https://www.cancer.gov"
    And "siteName" is set to "National Cancer Institute"
    And "channel" is set to "Search"
    And "contentGroup" is set to "Global Search"
    And "publishedDate" is set to "02/02/2011"
  When  user is searching for the term "tumor"
    And search results page displays results title "# results found for: " "tumor"
    And browser waits
  Then there should be an analytics event with the following details
      | key                                    | value                                                      |
      | type                                   | PageLoad                                                   |
      | event                                  | SitewideSearchApp:Load:SearchResults                             |
      | page.name                              | www.cancer.gov/?swKeyword=cancer                                 |
      | page.title                             | NCI Search Results                                 |
      | page.metaTitle                         | NCI Search Results - National Cancer Institute |
      | page.language                          | english                                                    |
      | page.type                              | nciAppModulePage                                           |
      | page.audience                          |                                                    |
      | page.channel                           | Search                                               |
      | page.contentGroup                      | Global Search                             |
      | page.publishedDate                     | 02/02/2011                                                 |
      | page.additionalDetails.numberResults   | (int)10094                                                    |
      | page.additionalDetails.searchKeyword   | tumor                                                       |
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Create the routes & url query hook
- [ ] Create the page components (results list, result item, infographic item, video item)
- [ ] Fetch results from API
- [ ] Add unit tests
- [ ] Add integration tests

### Technical Notes
- Link to current code for video/infographic label: https://github.com/NCIOCPL/search-results-app/blob/ticket/4-gh-actions-wf/src/components/results-list/results-list-item/ResultsListItem.jsx
