### ISSUE TITLE
Story: Definition Display

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/sitewide-search-app#5]
## As a content editor, I would like to display the definition of a term at the top of search results in order to provide more detailed information to users if their search term matches a term in NCI’s dictionary.

> **ESTIMATE** 5

### Acceptance Criteria

```gherkin
Scenario: English Dictionary Definition Display
    Given the user navigates to "/?swKeyword=metastasis"
     Then the page title is "NCI Search Results"
      And page subtitle "Results for: metastasis" appears below the page title
      And definition box appears with title "Definition:"
      And the word "metastasis" appears in the definition box, with the audio icon and pronunciation
      And the definition "The spread of cancer cells from the place where they first formed to another part of the body." appears in the definition box (the first sentence of the definition)
      And link to the definition page with text "More information on dictionary page" and href "https://www.cancer.gov/publications/dictionaries/cancer-terms/def/46710" in the definition box
      And a button to toggle the full definition appears in the definition box labelled "Show full definition"
     When user clicks on the full definition toggle button in the definition box
     Then full definition toggle button text turns to "Hide full definition"
    Given user is viewing the second page of results for "metastasis"
      And page subtitle "Results for: metastasis" appears below the page title
     Then the definition box no longer appears on the page
```

```gherkin
Scenario: English Dictionary Definition Display - no more information link (see notes)
    Given the user navigates to "/?swKeyword=tumor"
     Then the page title is "NCI Search Results"
      And page subtitle "Results for: tumor" appears below the page title
      And definition box appears with title "Definition:"
      And the word "metastasis" appears in the definition box, with the audio icon and pronunciation
      And the definition "An abnormal mass of tissue that results when cells divide more than they should or do not die when they should." appears in the definition box
      And link to the definition page with text "More information on dictionary page" does not display
      And a button to toggle the full definition appears in the definition box labelled "Show full definition"
     When user clicks on the full definition toggle button in the definition box
     Then full definition toggle button text turns to "Hide full definition"
```

```gherkin
  Scenario: English Dictionary Definition Display - no show/hide full definition button
    Given the user navigates to "/?swKeyword=caloric intake"
     Then the page title is "NCI Search Results"
      And page subtitle "Results for: caloric intake" appears below the page title
      And definition box appears with title "Definition:"
      And the word "caloric intake" appears in the definition box, with the audio icon and pronunciation
      And the definition "Refers to the number of calories (energy content) consumed." appears in the definition box
      And link to the definition page with text "More information on dictionary page" does not display
      And button to toggle the full definition in the definition box labelled "Show full definition" does not display
```

```gherkin
Scenario: Spanish Dictionary Definition Display
    Given the user navigates to "/?swKeyword=cáncer de mama"
     Then the page title is "Resultados"
      And page subtitle "Resultados para: cáncer de mama" appears below the page title
      And definition box appears with title "Definición:"
      And the word "cáncer de mama" appears in the definition box with the audio icon
      And the definition "Cáncer que se forma en los tejidos del seno (mama)." appears in the definition box
      And link to the definition page with text "Más información" and href "https://www.cancer.gov/espanol/publicaciones/diccionario/def/444971" in the definition box
      And a button to toggle the full definition appears in the definition box labelled "Mostrar toda la definición"
     When user clicks on the full definition toggle button in the definition box
     Then full definition toggle button text turns to "Ocultar toda la definición"
    Given user is viewing the second page of results for "cáncer de mama"
      And page subtitle "Resultados para: cáncer de mama" appears below the page title
     Then the definition box no longer appears on the page
```

```gherkin
Scenario: Spanish Dictionary Definition Display - no more information link
    Given the user navigates to "/?swKeyword=tumor"
     Then the page title is "Resultados"
      And page subtitle "Resultados para: tumor" appears below the page title
      And definition box appears with title "Definición:"
      And the word "tumor" appears in the definition box with the audio icon
      And the definition "Masa anormal de tejido que aparece cuando las células se multiplican más de lo debido o no se destruyen en el momento apropiado." appears in the definition box
      And link to the definition page with text "Más información" does not display
      And a button to toggle the full definition appears in the definition box labelled "Mostrar toda la definición"
     When user clicks on the full definition toggle button in the definition box
     Then full definition toggle button text turns to "Ocultar toda la definición"
```

```gherkin
  Scenario: Spanish Dictionary Definition Display - no show/hide full definition button
    Given the user navigates to "/?swKeyword=cáncer de la vagina en estadio lll"
     Then the page title is "Resultados"
      And page subtitle "Resultados para: cáncer de la vagina en estadio lll" appears below the page title
      And definition box appears with title "Definición:"
      And the word "cáncer de la vagina en estadio lll" appears in the definition box with the audio icon
      And the definition "El cáncer se diseminó hasta la pared de la pelvis." appears in the definition box
      And link to the definition page with text "Más información" and href "https://www.cancer.gov/espanol/publicaciones/diccionario/def/535780" in the definition box
      And button to toggle the full definition in the definition box labelled "Mostrar toda la definición" does not display
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

* Search term and definition must be exact match.
   * Spanish accents are not required.
* For `And a link to the definition page appears below the first sentence with the words "More information on dictionary page"` this link should be in the form, `<glossary_url>/def/<prettyurl_or_id>` where:
  * glossary_url is something like `https://colo.cancer.gov/publications/dictionaries/cancer-terms`
  * prettyurl_or_id is the pretty url name if available, otherwise use the id
* More information only appears if there are media or related resources for the term then the link should display 

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [x] Create `Definition` component
- [x] Fetch results from API
- [x] Apply styling
- [x] Add unit tests
- [x] Add integration tests

### Technical Notes
- More notes, or technical nuances/direction

**Comment by amydugan** [comment]
To Do: Decide on approach for CSS @arcepaul @seyilonge-nci
